# Usage:
#  Any service with the 'build' attribute specified will be built and tagged with the name in the 'image' attribute. (-f [--file])
#  > docker-compose -f docker-compose.nats.yml -f docker-compose.build.nats.yml build
#  > docker-compose -f docker-compose.nats.yml -f docker-compose.build.nats.yml build --no-cache
version: "3.7"

services:
  # Publishes to NATS.
  nats-publisher:
    # The context path is relative to the location of the Compose file, and the Dockerfile path is relative to the context.
    build:
      context: ./Nats.Publisher/
      dockerfile: ./Dockerfile
      args:
        BASE_OS_LAYER: mcr.microsoft.com/dotnet/core/runtime
        BASE_OS_LAYER_VERSION: 2.2
        BUILD_BASE_OS_LAYER: mcr.microsoft.com/dotnet/core/sdk
        BUILD_BASE_OS_LAYER_VERSION: 2.2

  # Subscribes to NATS.
  nats-subscriber:
    build:
      context: ./Nats.Subscriber/
      dockerfile: ./Dockerfile
      args:
        BASE_OS_LAYER: mcr.microsoft.com/dotnet/core/runtime
        BASE_OS_LAYER_VERSION: 2.2
        BUILD_BASE_OS_LAYER: mcr.microsoft.com/dotnet/core/sdk
        BUILD_BASE_OS_LAYER_VERSION: 2.2

  # Message-queue
  natsmq:
    build:
      context: ./NATS/
      dockerfile: ./Dockerfile
      args:
        BASE_OS_LAYER: mcr.microsoft.com/windows/nanoserver
        BASE_OS_LAYER_VERSION: 1903
        # The NAT Server will look for this environment variable. When set, it prevents the use of the service API to detect
        # if it is running in interactive mode or not, which is failing in the context of a Docker container.
        # (https://github.com/nats-io/gnatsd/issues/543)
        NATS_DOCKERIZED: 1
