# Usage:
#   Start the application.
#   > docker-compose -f docker-compose.yml -f docker-compose.hydra.yml up -d [--detach]
#
#   Stop the application.
#   > docker-compose -f docker-compose.yml -f docker-compose.hydra.yml down
version: "3.7"

services:
  ##################
  # Infrastructure #
  ##################
  # Hydra (OAuth2) #
  ##################
  # Run hydra-migrate ONLY from the command line!!!
  # See WARNING!!! below.
  hydra-migrate:
    image: veni-vidi-vici/hydra-1.10.1-sqlite:nanoserver-20H2
    isolation: process
    entrypoint: hydra
    # WARNING!!!
    # Before running this command on an existing database, create a back up.
    #
    # Options
    # -e [--read-from-env] - If set, reads the database connection string from the environment variable DSN or config file key dsn.
    # -y [--yes] - If set, all confirmation requests are accepted without user interaction.
    #
    # Options inherited from parent commands
    # -c [--config strings] - Path to one or more .json, .yaml, .yml, .toml config files. Values are loaded in the order provided, meaning that the last config file overwrites values from the previous config file.
    command: "migrate sql -e --yes"
    environment:
      DSN: "sqlite://C:/hydra-data/db.sqlite?_fk=true"
    volumes:
      - type: bind
        # The source is the host location, which needs to exist.
        source: C:\jct\Repos\Volumes\hydra\
        # The target is the container location, which does't need to exist, but the existing contents will be hidden if it does exist.
        target: C:\hydra-data\
    networks:
      - oauth
    restart: on-failure

  hydra:
    depends_on:
      - hydra-migrate
    image: veni-vidi-vici/hydra-1.10.1-sqlite:nanoserver-20H2
    isolation: process
    entrypoint: hydra
    command: "serve all --dangerous-force-http"
    environment:
      - SECRETS_SYSTEM='this_needs_to_be_the_same_always_and_also_very_$$3cuR3-._'
      # Set Data Source Name (DSN) for SQLite.
      - DSN='sqlite://C:/hydra-data/db.sqlite?_fk=true'
      # Must be set to the publicly available URL of ORY Hydra.
      - URLS_SELF_ISSUER='https://localhost:9000/'
      # Must be set to the URL of the consent provider.
      - URLS_CONSENT='http://localhost:9020/consent'
      # Must be set to the URL of the login provider.
      - URLS_LOGIN='http://localhost:9020/login'
    volumes:
      - type: bind
        # The source is the host location, which needs to exist.
        source: C:\jct\Repos\Volumes\hydra\
        # The target is the container location, which does't need to exist, but the existing contents will be hidden if it does exist.
        target: C:\hydra-data\
    ports:
        # ORY Hydra's public API (container)
      - target: 4444
        # Host
        published: 9000
        # Protocol (tcp or udp)
        protocol: tcp
        # ORY Hydra's administrative API (container)
      - target: 4445
        # Host
        published: 9001
        # Protocol (tcp or udp)
        protocol: tcp
    networks:
      - oauth
    restart: unless-stopped
