# Usage:
#   Start the application.
#   > docker-compose -f docker-compose.yml -f docker-compose.production.sqldb.yml up -d [--detach]
#
#   Stop the application.
#   > docker-compose -f docker-compose.yml -f docker-compose.production.sqldb.yml down
version: "3.7"

services:
  ##################
  # Infrastructure #
  ##################
  sqlexpress:
    labels:
      - "traefik.frontend.rule=Host:sqldb.com"
    ports:
        # SQL Server (container)
      - target: 1433
        # SQL Server (host) [By not specifying a host (published) port, an ephemeral host port is chosen.]
        # published: 1433
        # Protocol (tcp or udp)
        protocol: tcp
    volumes:
      - type: bind
        # The source is the host location, which needs to exist.
        source: c:\db\sqlexpress
        # The target is the container location, which does't need to exist, but the existing contents will be hidden if it does
        # exist.
        target: c:\db\sqlexpress



# Docker containers communicate among themselves in networks created, implicitly or through configuration,
# by Docker Compose. A service can communicate with another service on the same network by simply referencing
# it by container name and port (for example network-example-service:80), provided that the port has been made
# accessible through the expose keyword

# To reach a container from the host, the ports must be exposed declaratively through the ports keyword,
# which also allows us to choose if exposing the port differently in the host:

#networks:
#  back-end:
#    name: nat-backend

#
# Volumes can be specified as external so Docker will use existing volumes. Docker does not create any default volumes so if you
# use an external volume, you will need to create it on the host before running the application. But if you specify the volumes
# without any options, Docker will create them for you. For example,
#
#   volumes:
#     es-data:
#
# These volumes will store the data on the host rather than in the container's writable layer. They're not host-mounted volumes
# so although the data is stored on the local disk, you are not specifying the location. Each volume will write its data in the
# Docker data directory at C:\ProgramData\Docker.
#
# To use existing volumes, you need to specify the external attribute and optionally a name for the resource. With external
# resources declared, you can't just run the application using docker-compose up. Compose won't create volumes defined as
# external; they need to exist before the application starts. And if these volumes are required by the services, Docker won't
# create any containers either. To create basic volumes with default configurations,
#   docker volume create --name elasticsearch-data
#
#volumes:
##  elasticsearch-data:
#    driver_opts:
#      type: none
##      device: c:\docker-volumes\elasticsearch\data
#     o: bind
#  sqlexpress-data:
#    external:
#      name: sqlexpress-database
