apiVersion: v1
kind: Namespace
metadata:
  name: nats-namespace
# YAML files can contain multiple resource definitions separated by a line with three dashes.
---
##########
# Server #
##########
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-deployment
  namespace: nats-namespace
spec:
  # Only the current and previous revisions (ReplicaSets) are preserved.
  revisionHistoryLimit: 2
  # The desired number of pod instances.
  replicas: 1
  #stragedy:
  #  rollingUpdate:
      # How many pod instances are allowed to exist above the desired replica count.
  #    maxSurge: 1
      # How many pod instances can be unavailable relative to the desired replica count.
      # A value of 0 makes the deployment replace pods one by one.
  #    maxUnavailable: 1
    # When app does support running multiple versions in parallel.
  #  type: RollingUpdate
    # When app doesn't support running multiple versions in parallel (app becomes completely unavailable
    # for a short period of time).
    #type: Recreate
  # Pod selector.
  selector:
    matchExpressions:
      - key: deployment-label
        operator: In
        values:
          - nats
  # Pod template.
  template:
    metadata:
      # Must macth "Service" and "Deployment" labels.
      labels:
        deployment-label: nats
        service-label: nats
    spec:
      containers:
        - name: nats
          #image: veni-vidi-vici/nats-2.0.2:nanoserver-20H2
          image: nats:2.2.1
          ports:
            - name: client
              containerPort: 4222
              protocol: TCP
            - name: management
              containerPort: 8222
              protocol: TCP
            - name: cluster
              containerPort: 6222
              protocol: TCP
      restartPolicy: Always
---
#############
# Publisher #
#############
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-publisher-deployment
  namespace: nats-namespace
spec:
  # Only the current and previous revisions (ReplicaSets) are preserved.
  revisionHistoryLimit: 2
  # The desired number of pod instances.
  replicas: 1
  #stragedy:
  #  rollingUpdate:
      # How many pod instances are allowed to exist above the desired replica count.
  #    maxSurge: 1
      # How many pod instances can be unavailable relative to the desired replica count.
      # A value of 0 makes the deployment replace pods one by one.
  #    maxUnavailable: 1
    # When app does support running multiple versions in parallel.
  #  type: RollingUpdate
    # When app doesn't support running multiple versions in parallel (app becomes completely unavailable
    # for a short period of time).
    #type: Recreate
  # Pod selector.
  selector:
    matchExpressions:
      - key: deployment-label
        operator: In
        values:
          - nats
  # Pod template.
  template:
    metadata:
      # Must macth "Service" and "Deployment" labels.
      labels:
        deployment-label: nats
        service-label: nats
    spec:
      containers:
        - name: nats-publisher
          image: veni-vidi-vici/nats-publisher-1.0.0:dotnet-5.0-alpine
---
apiVersion: v1
kind: Service
metadata:
  name: nats-service
spec:
  type: ClusterIP
  ports:
    - name: without-tls
      # Host
      port: 5672
      # Pod
      targetPort: without-tls
      protocol: TCP
    - name: with-tls
      port: 5671
      targetPort: with-tls
      protocol: TCP
    - name: ui-admin
      port: 15672
      targetPort: ui-admin
      protocol: TCP
  selector:
    # Pod selector; all Pods with the service-label=nats label will be part of this service.
    service-label: nats
    sessionAffinity: None
